### ISSUE TITLE
Notice: Infinite loop in Highlight.php

### ISSUE THREAD

**Issue by assertchris** [spatie/commonmark-highlighter#3]
There's [an issue for it](https://github.com/scrivo/highlight.php/issues/33), but the bottom line is new installations of this library will pull in a version of the highlighter which has an infinite loop when rendering JS code blocks.

I have [a branch that fixes it](https://github.com/assertchris/highlight.php/tree/feature/add-overrun-protection), which I have submitted as a PR; but you might want to tag an older version in the meantime...

**Comment by sebastiandedeyne** [comment]
The highlight.php repo looks pretty active so I'm gonna give them a few day to get this sorted first. Gonna leave this issue open for visibility, and if nothing changes in the near future I'll specify a different version range.

Thanks for reporting!

**Comment by allejo** [comment]
The 7.3 incompatibility been fixed in [v9.13.1.1](https://github.com/scrivo/highlight.php/releases/tag/v9.13.1.1). The [`composer.json` for this repo seems to locked to 9.12.0.5](https://github.com/spatie/commonmark-highlighter/blob/1ac9ec97b45063515c69b32a7b7ab2d7e1f4295f/composer.json#L21) so that may need to change so this repo can pull a more recent version.

**Comment by freekmurze** [comment]
@assertchris Thanks for reporting this?
@allejo Thank you for letting me know this is fixed.

I tagged new release that requires v9.13.1.1

**Comment by assertchris** [comment]
Good job everyone! :D
